fix action

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -10,10 +10,12 @@ jobs:
     runs-on: self-hosted
 
     steps:
-      - uses: actions/checkout@v3
-
+      
       - name: Get Ip Address
         uses: echo "ip_address<<EOF" >> $GITHUB_ENV
+
+      - name: Checkout code
+        uses: actions/checkout@v2
 
       - name: Clean up Docker
         run: docker system prune -af --volumes
@@ -42,6 +44,28 @@ jobs:
           echo "::set-output name=content::$(cat changes.html | tr -d '\n')"
 
       - name: Send message to Slack
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$(echo $CONTENT | jq -R .)\"}" https://hooks.slack.com/services/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
+        uses: fjogeleit/http-request-action@v1.2.0
+        with:
+          url: https://hooks.slack.com/services/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
+          method: POST
+          headers: '{"Content-Type":"application/json"}'
+          data: '{"text": "${{ steps.read_html.outputs.content }}"}'
 
+      - name: Read HTML file
+        id: read_html
+        run: |
+          FILE_PATH="changes.html"
+          if [ -f "$FILE_PATH" ]; then
+            echo "File contents:"
+            CONTENT=$(cat "$FILE_PATH")
+            echo "html_content<<EOF" >> $GITHUB_ENV
+            echo "$CONTENT" >> $GITHUB_ENV
+            echo "EOF" >> $GITHUB_ENV
+          else
+            echo "File not found!"
+            exit 1
+          fi
+
+      - name: Send message to Slack
+        run: |
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy çıkıldı. https://test.otomas.app\n'"${{ env.html_content }}"'"}' https://hooks.slack.com/services/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
